// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3913bKfEhRw7g1E3eJhLsUUqwl0sUmo',
    appId: '1:334731624903:android:877ba2884ba107f6ac19e2',
    messagingSenderId: '334731624903',
    projectId: 'fight-gonggang-d1a8d',
    storageBucket: 'fight-gonggang-d1a8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74o6QoFzugtIfQN_-wC0hRCByGOTKV9I',
    appId: '1:334731624903:ios:a730a144c064e410ac19e2',
    messagingSenderId: '334731624903',
    projectId: 'fight-gonggang-d1a8d',
    storageBucket: 'fight-gonggang-d1a8d.appspot.com',
    iosBundleId: 'com.sm5.fightingGonggang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74o6QoFzugtIfQN_-wC0hRCByGOTKV9I',
    appId: '1:334731624903:ios:0da8127e947d8c04ac19e2',
    messagingSenderId: '334731624903',
    projectId: 'fight-gonggang-d1a8d',
    storageBucket: 'fight-gonggang-d1a8d.appspot.com',
    iosBundleId: 'com.sm5.fightingGonggang.RunnerTests',
  );
}
